"""add portfolio_items table

Revision ID: a56938bf16cd
Revises: 12ee55b447b0
Create Date: 2026-06-25 16:03:11.807336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56938bf16cd'
down_revision = '12ee55b447b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('valor_investido', sa.Float(), nullable=False),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('pct_cdi', sa.Float(), nullable=True),
    sa.Column('spread_ipca', sa.Float(), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('preco_entrada', sa.Float(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_items')
    # ### end Alembic commands ###
